_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.18.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
iterations:
    value: 300
society:
    value: util_society
society_num:
    value: 54
timestamp:
    value: "2024-09-26"
